
package uk.co.o2.soa.sendmessageservice_1_1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendMessage", targetNamespace = "http://soa.o2.co.uk/sendmessageservice_1_1", wsdlLocation = "sendmessageservice_1_1.wsdl")
public class SendMessage
    extends Service
{

    private final static URL SENDMESSAGE_WSDL_LOCATION;
    private final static WebServiceException SENDMESSAGE_EXCEPTION;
    private final static QName SENDMESSAGE_QNAME = new QName("http://soa.o2.co.uk/sendmessageservice_1_1", "SendMessage");

    static {
        SENDMESSAGE_WSDL_LOCATION = uk.co.o2.soa.sendmessageservice_1_1.SendMessage.class.getResource("sendmessageservice_1_1.wsdl");
        WebServiceException e = null;
        if (SENDMESSAGE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'sendmessageservice_1_1.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SENDMESSAGE_EXCEPTION = e;
    }

    public SendMessage() {
        super(__getWsdlLocation(), SENDMESSAGE_QNAME);
    }

    public SendMessage(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDMESSAGE_QNAME, features);
    }

    public SendMessage(URL wsdlLocation) {
        super(wsdlLocation, SENDMESSAGE_QNAME);
    }

    public SendMessage(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDMESSAGE_QNAME, features);
    }

    public SendMessage(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMessage(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendMessagePortType
     */
    @WebEndpoint(name = "SendMessagePortType")
    public SendMessagePortType getSendMessagePortType() {
        return super.getPort(new QName("http://soa.o2.co.uk/sendmessageservice_1_1", "SendMessagePortType"), SendMessagePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMessagePortType
     */
    @WebEndpoint(name = "SendMessagePortType")
    public SendMessagePortType getSendMessagePortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.o2.co.uk/sendmessageservice_1_1", "SendMessagePortType"), SendMessagePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDMESSAGE_EXCEPTION!= null) {
            throw SENDMESSAGE_EXCEPTION;
        }
        return SENDMESSAGE_WSDL_LOCATION;
    }

}
